---
name: nginx-node-load-balancer  # name of the compose project
services:
 web1:
  build: ./node-server
  hostname: web1
 web2:
  build: ./node-server
  hostname: web2
 nginx:
  build: ./nginx-config
  depends_on:
   - web1
   - web2
  ports:
   - "80:80"
  
  